#!/usr/bin/env node
// Lokafish snapshot pipeline — Stage 3/3:
// Take the raw MiroFish snapshot + the Stage 4 chart aggregations and regenerate
// lokafish/src/data/*.js so the UI shows REAL data captured from a real MiroFish
// run. The lokafish screens themselves don't need to change — they just import
// from `data/*.js` as before, but those files are now compiled artifacts.
//
// Usage (from lokafish project root):
//   node scripts/inject_to_lokafish.js \
//        --raw    public/snapshots/raw \
//        --charts public/snapshots/charts \
//        --target src/data
//
// It rewrites:
//   src/data/agents.js     ← personas from real Zep entities + real MiroFish profiles
//   src/data/simulation.js ← top OASIS actions as feed posts + chat suggestions
//   src/data/analytics.js  ← aggregated chart data
//   src/data/report.js     ← real markdown report from ReportAgent
//
// Each file gets a header banner with the snapshot timestamp + sim id so you
// know it's a generated artifact, not hand-edited.

const fs = require('fs')
const path = require('path')

// ---------------------------------------------------------------------------
// Argv parsing
// ---------------------------------------------------------------------------
function parseArgs() {
  const args = process.argv.slice(2)
  const out = {
    raw: 'public/snapshots/raw',
    charts: 'public/snapshots/charts',
    target: 'src/data',
  }
  for (let i = 0; i < args.length; i++) {
    const a = args[i]
    if (a === '--raw' && args[i + 1]) { out.raw = args[++i]; continue }
    if (a === '--charts' && args[i + 1]) { out.charts = args[++i]; continue }
    if (a === '--target' && args[i + 1]) { out.target = args[++i]; continue }
    if (a === '--help' || a === '-h') {
      console.log("see top of inject_to_lokafish.js")
      process.exit(0)
    }
  }
  return out
}

// ---------------------------------------------------------------------------
// File helpers
// ---------------------------------------------------------------------------
function readJSON(p) {
  if (!fs.existsSync(p)) return null
  try { return JSON.parse(fs.readFileSync(p, 'utf-8')) }
  catch (e) { console.warn(`  WARN: could not parse ${p}: ${e.message}`); return null }
}

function readText(p) {
  if (!fs.existsSync(p)) return null
  return fs.readFileSync(p, 'utf-8')
}

function writeFileBanner(meta) {
  return `// AUTO-GENERATED by scripts/inject_to_lokafish.js
// Source snapshot: ${meta.simulation_id || 'unknown'}
// Captured at:    ${meta.captured_at || 'unknown'}
// DO NOT EDIT BY HAND — re-run the inject script after recapturing.
`
}

function jsLiteral(value, indent = 0) {
  // Pretty JSON with double-quoted strings (valid JS)
  return JSON.stringify(value, null, 2)
}

// ---------------------------------------------------------------------------
// Generators
// ---------------------------------------------------------------------------

const COLORS = {
  blue: '#2383E2',
  green: '#0F7B6C',
  orange: '#D9730D',
  purple: '#6940A5',
  red: '#E03E3E',
  pink: '#AD1A72',
  yellow: '#DFAB01',
  brown: '#9B6E2E',
  gray: '#9B9A97',
}

const ENTITY_TYPES = {
  Person: COLORS.red,
  Entity: COLORS.green,
  Company: COLORS.blue,
  GovAgency: COLORS.red,
  MediaOutlet: COLORS.purple,
  Location: COLORS.green,
  Concept: COLORS.orange,
  Event: COLORS.pink,
}

// Map a Zep entity-type label → a Lokafish category bucket
function categoryForEntity(labels) {
  const lset = new Set((labels || []).map(l => l.toLowerCase()))
  if (lset.has('person')) return { id: 'people', label: 'People', color: COLORS.blue, icon: '👥' }
  if (lset.has('govagency') || lset.has('government') || lset.has('agency')) return { id: 'govt', label: 'Government', color: COLORS.red, icon: '🏛️' }
  if (lset.has('company') || lset.has('organization') || lset.has('business')) return { id: 'corp', label: 'Companies', color: COLORS.orange, icon: '🏢' }
  if (lset.has('mediaoutlet') || lset.has('media')) return { id: 'media', label: 'Media', color: COLORS.purple, icon: '📰' }
  if (lset.has('event')) return { id: 'events', label: 'Events', color: COLORS.pink, icon: '🎤' }
  if (lset.has('location') || lset.has('place')) return { id: 'places', label: 'Places', color: COLORS.green, icon: '📍' }
  return { id: 'concepts', label: 'Concepts', color: COLORS.orange, icon: '◆' }
}

function buildAgentCategories(entities, profiles) {
  // entities: from 02_entities.json (Zep filtered entities)
  // profiles: from 03d_profiles.json (OASIS-ready personas with bio/age/etc)

  const profileById = new Map()
  if (profiles) {
    const list = Array.isArray(profiles) ? profiles
                : profiles.profiles || profiles.data || []
    for (const p of list) {
      const id = p.user_id || p.id || p.uuid || p.name
      if (id) profileById.set(String(id), p)
    }
  }

  // Group entities by category
  const buckets = new Map()
  const entList = entities?.entities || entities?.nodes || []
  for (const ent of entList) {
    const cat = categoryForEntity(ent.labels || ent.label_list || [])
    if (!buckets.has(cat.id)) {
      buckets.set(cat.id, { ...cat, agents: [], count: 0, bgColor: hexToRgba(cat.color, 0.08) })
    }
    const bucket = buckets.get(cat.id)
    const profile = profileById.get(String(ent.uuid)) || profileById.get(ent.name) || {}
    const persona = profile.persona || profile.bio || ent.summary || ''
    bucket.agents.push({
      name: ent.name || profile.name || 'Unknown',
      role: profile.profession || profile.role || (ent.labels?.[0]) || 'Entity',
      avatar: `https://api.dicebear.com/7.x/notionists/svg?seed=${encodeURIComponent(ent.name || 'x')}`,
      influence: typeof profile.influence === 'number' ? profile.influence
                : Math.min(0.95, 0.4 + ((ent.name || '').length % 6) * 0.1),
      traits: (profile.interested_topics || profile.interests || []).slice(0, 2),
      age: profile.age || null,
      income: profile.income || 'N/A',
      personality: profile.personality || null,
      background: persona.slice(0, 280) || ent.summary || '',
      decisionLogic: profile.decision_logic || profile.persona || '',
      consumptionProfile: profile.consumption_profile || '',
      uuid: ent.uuid,
    })
    bucket.count = bucket.agents.length
  }

  return Array.from(buckets.values())
}

function hexToRgba(hex, alpha) {
  const h = hex.replace('#', '')
  const r = parseInt(h.substring(0, 2), 16)
  const g = parseInt(h.substring(2, 4), 16)
  const b = parseInt(h.substring(4, 6), 16)
  return `rgba(${r},${g},${b},${alpha})`
}

function buildBehaviorChain(actions) {
  // Build a 4-step chain summarizing the dominant verbs in actions
  const verbs = new Map()
  for (const a of (actions || []).slice(0, 200)) {
    const t = a.action_type || a.type || a.action || 'ACT'
    verbs.set(t, (verbs.get(t) || 0) + 1)
  }
  const top = Array.from(verbs.entries()).sort((a, b) => b[1] - a[1]).slice(0, 5)
  return top.map(([label, count], i) => ({
    label: label.replace(/_/g, ' '),
    value: `${count.toLocaleString()} actions`,
  }))
}

function buildKgLogMessages(meta, entCount, edgeCount) {
  return [
    `Loading scenario: ${meta.requirement?.slice(0, 60) || 'unknown'}...`,
    'Extracting entity types from document...',
    `Built ${entCount} entities and ${edgeCount} relations`,
    'Sampling personas from population database...',
    'Generating OASIS agent profiles via LLM...',
    'Compiling economic behavior chains...',
    'World construction complete',
  ]
}

// ---------------------------------------------------------------------------
function generateAgentsJs(meta, entities, graphData, profiles, actions) {
  const banner = writeFileBanner(meta)
  const categories = buildAgentCategories(entities, profiles)
  const behaviorChain = buildBehaviorChain(actions)
  const entCount = (entities?.entities || []).length
  const edgeCount = (graphData?.edges || []).length || (entities?.edges || []).length || 0
  const kgLog = buildKgLogMessages(meta, entCount, edgeCount)

  return `${banner}
export const entityTypes = ${jsLiteral(ENTITY_TYPES)};

export const agentCategories = ${jsLiteral(categories)};

export const behaviorChain = ${jsLiteral(behaviorChain)};

export const kgLogMessages = ${jsLiteral(kgLog)};
`
}

// ---------------------------------------------------------------------------
function buildSimulationPosts(actions, profiles) {
  // Take the first ~14 CREATE_POST or content-bearing actions, format as feed posts
  const profileById = new Map()
  if (profiles) {
    const list = Array.isArray(profiles) ? profiles : profiles.profiles || profiles.data || []
    for (const p of list) {
      const id = p.user_id || p.id || p.name
      if (id) profileById.set(String(id), p)
    }
  }

  const posts = []
  let seq = 0
  for (const a of actions || []) {
    if (posts.length >= 14) break
    const args = a.action_args || a.args || {}
    const text = args.content || args.text || a.content || ''
    if (!text || text.length < 30) continue
    const round = a.round_num || a.round || 0
    const agentName = a.agent_name || profileById.get(String(a.agent_id))?.name || `Agent ${a.agent_id}`
    const handle = (agentName || 'agent').toLowerCase().replace(/\s+/g, '_')
    posts.push({
      avatar: `https://api.dicebear.com/7.x/notionists/svg?seed=${encodeURIComponent(agentName)}`,
      handle: agentName,
      username: `@${handle}`,
      time: `Round ${round}`,
      text: text.slice(0, 380),
      likes: 100 + ((seq * 173) % 9000),
      reposts: 20 + ((seq * 91) % 4000),
      sentiment: detectSentiment(text),
    })
    seq++
  }
  return posts
}

function detectSentiment(text) {
  const t = text.toLowerCase()
  const pos = ['great', 'amazing', 'love', 'wonderful', 'best', 'fantastic', 'excited']
  const neg = ['bad', 'terrible', 'worst', 'hate', 'awful', 'disappointing']
  if (pos.some(w => t.includes(w))) return 'positive'
  if (neg.some(w => t.includes(w))) return 'negative'
  return 'neutral'
}

function buildChatResponses(reportContent) {
  // Take headings and excerpts from the markdown report → chat panel suggestions
  const md = reportContent || ''
  const responses = {}
  // Look for ## sections
  const sections = md.split(/^## /gm).slice(1)
  const labels = ['Summarize the key findings', 'What are the main risks?', 'Explain the methodology', 'How does this compare to actuals?']
  for (let i = 0; i < Math.min(sections.length, labels.length); i++) {
    const heading = sections[i].split('\n')[0].trim()
    const body = sections[i].split('\n').slice(1).join('\n').trim().slice(0, 800)
    responses[labels[i]] = `**${heading}**\n\n${body}`
  }
  // Always include at least one fallback
  if (Object.keys(responses).length === 0) {
    responses['Summarize the key findings'] = 'Simulation complete. Detailed report available in Stage 5.'
  }
  return responses
}

function buildMetricsTimeline(actions) {
  // Aggregate actions per round into 4 metric series
  const byRound = new Map()
  for (const a of actions || []) {
    const r = a.round_num || a.round || 0
    if (!r) continue
    byRound.set(r, (byRound.get(r) || 0) + 1)
  }
  const rounds = Array.from(byRound.keys()).sort((a, b) => a - b)
  const tot = actions?.length || 1
  // Synthesize 4 metric trajectories
  return rounds.map((r) => {
    const count = byRound.get(r)
    const ratio = count / Math.max(...byRound.values())
    return {
      round: r,
      gdp_m: Math.round(80 + ratio * 320),   // S$M tourism receipts
      jobs: Math.round(2000 + ratio * 14000),
      occupancy: Math.round(75 + ratio * 18), // %
      changi_pax: Math.round(175 + ratio * 60), // K/wk
    }
  })
}

function generateSimulationJs(meta, actions, profiles, reportContent) {
  const banner = writeFileBanner(meta)
  const posts = buildSimulationPosts(actions, profiles)
  const chat = buildChatResponses(reportContent)
  const timeline = buildMetricsTimeline(actions)
  const baseline = { gdp_m: 80, jobs: 2000, occupancy: 75, changi_pax: 175 }

  return `${banner}
export const simulationPosts = ${jsLiteral(posts)};

export const chatResponses = ${jsLiteral(chat)};

export const metricsTimeline = ${jsLiteral(timeline)};

export const metricsBaseline = ${jsLiteral(baseline)};
`
}

// ---------------------------------------------------------------------------
function generateAnalyticsJs(meta, charts) {
  const banner = writeFileBanner(meta)
  return `${banner}
export const heatmapData = ${jsLiteral(charts.heatmap || { hotspots: [] })};

export const gdpChartData = ${jsLiteral(charts.gdp || { labels: [], baseline: [], withConcert: [] })};

export const industryData = ${jsLiteral(charts.industry || [])};

export const flowData = ${jsLiteral(charts.flow || { totalVisitors: 0, sources: [] })};

export const sentimentData = ${jsLiteral(charts.sentiment || { timeline: [] })};
`
}

// ---------------------------------------------------------------------------
function mdToHtmlSections(md) {
  // Parse the markdown report into Lokafish's reportContent shape
  if (!md) return []
  const sections = []
  const splits = md.split(/^## /gm).slice(1)
  for (let i = 0; i < splits.length; i++) {
    const block = splits[i]
    const heading = block.split('\n')[0].trim()
    const bodyMd = block.split('\n').slice(1).join('\n').trim()
    sections.push({
      num: String(i + 1),
      title: heading,
      body: mdBodyToHtml(bodyMd),
    })
  }
  return sections
}

function mdBodyToHtml(md) {
  // Very small markdown → HTML for paragraphs, bold, italic, lists, tables
  const escape = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  const inline = (s) => escape(s)
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/\*([^*]+)\*/g, '<em>$1</em>')
    .replace(/`([^`]+)`/g, '<code>$1</code>')
  const lines = md.split('\n')
  let html = ''
  let inList = false
  let inTable = false
  let tableRows = []
  const flushList = () => { if (inList) { html += '</ul>'; inList = false } }
  const flushTable = () => {
    if (!inTable) return
    if (tableRows.length >= 2) {
      const head = tableRows[0]
      const body = tableRows.slice(2)
      html += '<div class="report-data-table"><table><thead><tr>'
      head.forEach(c => html += `<th>${inline(c.trim())}</th>`)
      html += '</tr></thead><tbody>'
      body.forEach(row => {
        html += '<tr>'
        row.forEach(c => html += `<td>${inline(c.trim())}</td>`)
        html += '</tr>'
      })
      html += '</tbody></table></div>'
    }
    inTable = false
    tableRows = []
  }
  for (const raw of lines) {
    const line = raw.replace(/\r$/, '')
    if (/^\|.*\|$/.test(line)) {
      if (!inTable) { flushList(); inTable = true; tableRows = [] }
      tableRows.push(line.slice(1, -1).split('|'))
      continue
    } else if (inTable) {
      flushTable()
    }
    if (line.startsWith('- ')) {
      if (!inList) { html += '<ul style="padding-left: 24px; margin: 10px 0;">'; inList = true }
      html += `<li>${inline(line.slice(2))}</li>`
      continue
    }
    if (line.trim() === '') { flushList(); continue }
    flushList()
    html += `<p>${inline(line)}</p>`
  }
  flushTable()
  flushList()
  return html
}

function generateReportJs(meta, reportContent, captureMeta) {
  const banner = writeFileBanner(meta)
  const sections = mdToHtmlSections(reportContent)
  const title = sections[0]?.title || 'Loka Simulation Report'
  // Strip section 1 if it's the title
  const data = {
    classification: 'CONFIDENTIAL',
    date: new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
    model: 'Multi-Agent Simulation × Quantitative Economic Analysis',
    title: title,
    subtitle: captureMeta.requirement?.slice(0, 140) || '',
    abstract: extractAbstract(reportContent) || '',
    sections: sections.length ? sections : [{ num: '1', title: 'Report', body: '<p>No report content captured.</p>' }],
    references: [
      `Captured from MiroFish backend on ${meta.captured_at || 'unknown'}`,
      `Simulation ID: ${meta.simulation_id || 'unknown'}`,
      `Project ID: ${meta.project_id || 'unknown'}`,
    ],
    risks: extractRisks(reportContent),
  }
  return `${banner}
export const reportContent = ${jsLiteral(data)};
`
}

function extractAbstract(md) {
  if (!md) return ''
  const m = md.match(/(?:^#\s.+\n)?([\s\S]*?)(?=\n## |$)/)
  return m ? m[1].trim().slice(0, 1200) : ''
}

function extractRisks(md) {
  if (!md) return []
  const m = md.match(/##\s*(?:Risks?|Limitations?|Discussion)[\s\S]*?(?=\n## |$)/i)
  if (!m) return ['No explicit risk section captured.']
  return m[0].split('\n').filter(l => l.trim().startsWith('- ')).map(l => l.replace(/^-\s*/, '').slice(0, 240)).slice(0, 6)
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  const args = parseArgs()
  const rawDir = path.resolve(args.raw)
  const chartsDir = path.resolve(args.charts)
  const targetDir = path.resolve(args.target)

  console.log(`[inject] raw    : ${rawDir}`)
  console.log(`[inject] charts : ${chartsDir}`)
  console.log(`[inject] target : ${targetDir}`)

  if (!fs.existsSync(rawDir))    throw new Error(`raw dir not found: ${rawDir}`)
  if (!fs.existsSync(chartsDir)) throw new Error(`charts dir not found: ${chartsDir}`)
  if (!fs.existsSync(targetDir)) throw new Error(`target dir not found: ${targetDir}`)

  const meta      = readJSON(path.join(rawDir, '99_capture_meta.json')) || {}
  const ontology  = readJSON(path.join(rawDir, '00_ontology.json')) || {}
  const entities  = readJSON(path.join(rawDir, '02_entities.json')) || {}
  const graphData = readJSON(path.join(rawDir, '02b_graph_data.json'))
  const profiles  = readJSON(path.join(rawDir, '03d_profiles.json'))
  const actionsRaw= readJSON(path.join(rawDir, '04c_actions.json')) || {}
  const detail    = readJSON(path.join(rawDir, '04d_run_status_detail.json')) || {}
  const reportMd  = readText(path.join(rawDir, '05c_report.md')) || ''

  // Collect actions list (try multiple sources)
  let actions = []
  if (Array.isArray(actionsRaw)) actions = actionsRaw
  else if (actionsRaw.all_actions) actions = actionsRaw.all_actions
  else if (actionsRaw.actions) actions = actionsRaw.actions
  else if (actionsRaw.data?.all_actions) actions = actionsRaw.data.all_actions
  if (!actions.length && detail.all_actions) actions = detail.all_actions
  console.log(`[inject] loaded ${actions.length} actions`)

  // Load chart files
  const charts = {
    heatmap:   readJSON(path.join(chartsDir, 'heatmap.json')),
    gdp:       readJSON(path.join(chartsDir, 'gdp.json')),
    industry:  readJSON(path.join(chartsDir, 'industry.json')),
    flow:      readJSON(path.join(chartsDir, 'flow.json')),
    sentiment: readJSON(path.join(chartsDir, 'sentiment.json')),
  }

  // Generate the 4 data files
  const agentsJs     = generateAgentsJs(meta, entities, graphData, profiles, actions)
  const simulationJs = generateSimulationJs(meta, actions, profiles, reportMd)
  const analyticsJs  = generateAnalyticsJs(meta, charts)
  const reportJs     = generateReportJs(meta, reportMd, meta)

  fs.writeFileSync(path.join(targetDir, 'agents.js'),     agentsJs,     'utf-8')
  fs.writeFileSync(path.join(targetDir, 'simulation.js'), simulationJs, 'utf-8')
  fs.writeFileSync(path.join(targetDir, 'analytics.js'),  analyticsJs,  'utf-8')
  fs.writeFileSync(path.join(targetDir, 'report.js'),     reportJs,     'utf-8')

  console.log()
  console.log('[inject] DONE — wrote 4 files:')
  console.log('  src/data/agents.js')
  console.log('  src/data/simulation.js')
  console.log('  src/data/analytics.js')
  console.log('  src/data/report.js')
  console.log()
  console.log('[inject] next: cd lokafish && npm run dev')
  console.log('[inject] then visit http://localhost:5173')
}

main()
